services:
  - type: web
    name: intelligent-ran-analytics-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: FRONTEND_ORIGIN
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: MONGODB_URI
        sync: false
      - key: MONGODB_DATABASE
        value: ran_analytics
